// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deletefeedfollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeedFollowsPair = `-- name: DeleteFeedFollowsPair :exec
DELETE FROM feed_follows
WHERE user_id = $1
  AND feed_id = $2
`

type DeleteFeedFollowsPairParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFeedFollowsPair(ctx context.Context, arg DeleteFeedFollowsPairParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowsPair, arg.UserID, arg.FeedID)
	return err
}
