// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getfeednamefromid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedNameById = `-- name: GetFeedNameById :one
SELECT name FROM feeds
where id = $1
`

func (q *Queries) GetFeedNameById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getFeedNameById, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
