// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getnextfeed.sql

package database

import (
	"context"
)

const getNextFeedtoFetch = `-- name: GetNextFeedtoFetch :one
SELECT id, name, url, user_id, last_fetched_at, created_at, updated_at
FROM feeds
ORDER BY last_fetched_at ASC
LIMIT 1
`

func (q *Queries) GetNextFeedtoFetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedtoFetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
